INCLUDE(InstallRequiredSystemLibraries)

IF (WIN32)
	SET(CPACK_GENERATOR "NSIS")
ELSE()
	SET(CPACK_GENERATOR "TGZ;DEB")
	SET(CPACK_SET_DESTDIR ON)
ENDIF()

SET(CPACK_PACKAGE_CONTACT "Julien Renggli") # Required
#SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Julien Renggli")

INCLUDE(CPack)
